# Generated by Django 5.1 on 2024-08-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('foto', models.ImageField(upload_to='clientes')),
            ],
        ),
    ]
