# Generated by Django 5.1 on 2024-08-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_sobre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='introducao')),
            ],
        ),
    ]
