# Generated by Django 5.1 on 2024-08-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_introducao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('endereco_1', models.CharField(max_length=100)),
                ('endereco_2', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='contato')),
            ],
        ),
    ]
