# Generated by Django 5.1 on 2024-08-12 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Quadro_1',
            fields=[
                ('portfolio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.portfolio')),
            ],
            bases=('portfolio.portfolio',),
        ),
        migrations.CreateModel(
            name='Quadro_2',
            fields=[
                ('portfolio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.portfolio')),
            ],
            bases=('portfolio.portfolio',),
        ),
        migrations.CreateModel(
            name='Quadro_3',
            fields=[
                ('portfolio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.portfolio')),
            ],
            bases=('portfolio.portfolio',),
        ),
        migrations.CreateModel(
            name='Quadro_4',
            fields=[
                ('portfolio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.portfolio')),
            ],
            bases=('portfolio.portfolio',),
        ),
    ]
