# Generated by Django 5.1 on 2024-08-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolio_quadro_1_quadro_2_quadro_3_quadro_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='alt',
            field=models.CharField(default='Fotografia', max_length=50),
            preserve_default=False,
        ),
    ]
